# I Strongly advice you to put those data in an ansible-vault file.
# ansible-vault encrypt password.yml
password:
  vsphere: <vSphere Password>
  template: <VM Template Password>
  awx: <AWX Password>
  vpn:
    <username>: <password>