---
# Vars that could be override:
#   - regen_vm_template: If Set to true, Isos will re-downloaded, preseed regenerated and packer templates relaunched

- name: Deploy vPloy
  hosts: localhost
  connection: local
  gather_facts: no
  
- import_playbook: playbooks/01-dependencies.yml
  tags:
  - dependencies

- import_playbook: playbooks/02-keys.yml
  tags:
  - keys

- import_playbook: playbooks/03-isos.yml
  vars:
    regen_vm_template: false
  tags:
  - isos

- import_playbook: playbooks/04-preseed.yml
  vars:
    regen_vm_template: false
  tags:
  - preseed

- import_playbook: playbooks/05-prepare_infra.yml
  vars:
    regen_vm_template: false
  tags:
  - prepare_infra

- import_playbook: playbooks/06-packer.yml
  vars:
    regen_vm_template: false
  tags:
  - packer

- import_playbook: playbooks/07-deploy_management.yml

- import_playbook: playbooks/08-install_awx.yml
  tags:
  - awx

- import_playbook: playbooks/09-deploy_infra.yml