---
- name: Destroy Infrastructures
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../config/infra/vsphere.yml
    - ../../config/infra/passwords.yml
  tasks:

  - name: Destroy Infra - List infrastructure directory
    find:
      paths: ../../config/infra
      file_type: directory
      excludes: 'template_factory,management'
    register: infras
    tags:
      - always

  - name: Destroy Infra - Create List of Infrastructure
    set_fact:
      infraNames: "{{ infras.files | map(attribute='path') | map('basename') | list }}"
    tags:
      - always

  - name: Destroy Infra - Include Playbook infrastructures
    include_tasks: 
      file: "infra/{{ item }}.yml"
      apply:
        tags:
          - destroy
          - destroy_infra
          - "{{ item }}"
    with_items: "{{ infraNames }}"
    tags:
      - always
