
# Management is a special infrastructure that have to be deployed first
- name: "{{ item }} - Set Infra Name Fact"
  set_fact:
     infra_name: "{{ item }}"
  tags:
    - always

- name: "{{ infra_name }} - Load Configs"
  include: infra/_config.yml
  tags:
    - always

- name: "{{ infra_name }} - Launch Terraform"
  terraform:
    project_path: ../terraform/infra/{{ infra_name }}
    state: present
    force_init: yes
    variables:
      vsphere-address: "{{ vsphere.address }}"
      vsphere-username: "{{ vsphere.username }}"
      vsphere-password: "{{ password.vsphere }}"
      vsphere-allow_unverified_ssl: "{{ vsphere.allow_unverified_ssl | lower }}"
      vsphere-datacenter: "{{ vsphere.datacenter }}"
      vsphere-cluster: "{{ vsphere.cluster }}"
      vsphere-network-pg-public: "{{ vsphere.network.public_pg }}"
      infra-name: "{{ infra_name }}"
      dns-domain: "{{ dns.domain }}"
      dns-nameservers: "{{ dns.nameservers | join(',') }}"
      network-public-gateway: "{{ network.gateway }}"
      network-public-ip: "{{ network.public_ip }}"
      network-priv-range: "{{ network.private_range }}"

- name: "{{ infra_name }} - Add Gateway to Ansible Inventory"
  add_host:
    hostname: "{{ infra_name }}-gateway"
    ansible_host: "{{ network.public_ip | ipaddr('address') }}"
    ansible_port: "22"
    ansible_user: "ansible"
    ansible_ssh_private_key_file: "generated/keys/ansible"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become_pass: "{{ password.template }}"
  tags:
    - always

- name: "{{ infra_name }} - Add Bastion to Ansible Inventory"
  add_host:
    hostname: "{{ infra_name }}-bastion"
    ansible_host: "{{ network.public_ip | ipaddr('address') }}"
    ansible_port: "22002"
    ansible_user: "ansible"
    ansible_ssh_private_key_file: "generated/keys/ansible"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become_pass: "{{ password.template }}"
  tags:
    - always

- name: "{{ infra_name }} - Add AWX to Ansible Inventory"
  add_host:
    hostname: "{{ infra_name }}-awx"
    ansible_host: "{{ network.public_ip | ipaddr('address') }}"
    ansible_port: "22003"
    ansible_user: "ansible"
    ansible_ssh_private_key_file: "generated/keys/ansible"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become_pass: "{{ password.template }}"
  tags:
    - always