- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - distribution
      - distribution_major_version
      - distribution_release
      - distribution_version

- name: Management AWX - Install Package Dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    autoremove: yes
    cache_valid_time: 3600
    install_recommends: no
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Management AWX - Add Ansible Apt Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
    state: present

- name: Management AWX - Add Ansible SourceList
  apt_repository:
    repo: deb [arch=amd64] http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
    state: present

- name: Management AWX - Add Docker Apt Key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Management AWX - Add Docker SourceList
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Management AWX - Install AWX Package Dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    autoremove: yes
    cache_valid_time: 3600
    install_recommends: no
  vars:
    packages:
    - docker-ce
    - docker-compose
    - ansible
    - git
    - python-dev
    - python-setuptools
    - python-pip
    - tar

- name: Management AWX - Install PIP docker-compose
  pip:
    name: docker-compose
    state: present