- name: Configure Awx - Download AWX
  git:
    repo: https://github.com/ansible/awx
    dest: /home/ansible/awx
    update: no

# Required else AWX doesn't restart
# https://github.com/ansible/awx/issues/3705
- name: Configure Awx - Change Docker Compose Dir
  lineinfile:
    destfile: "/home/ansible/awx/installer/inventory"
    regexp: '^#?\s*docker_compose_dir=.*$'
    line: "docker_compose_dir=/var/lib/awxcompose"
    state: present

- name: Configure Awx - Change Postgres Data Dir
  lineinfile:
    destfile: "/home/ansible/awx/installer/inventory"
    regexp: '^#?\s*postgres_data_dir=.*$'
    line: "postgres_data_dir=/var/pgdocker"
    state: present

- name: Configure Awx - Change Postgres Password
  lineinfile:
    destfile: "/home/ansible/awx/installer/inventory"
    regexp: '^#?\s*pg_password=.*$'
    line: "pg_password={{ pwd_alias }}"
    state: present
  vars:
    pwd_alias: "{{ lookup('password', '/dev/null length=25 chars=ascii_letters') }}"

- name: Configure Awx - Change Secret Key
  lineinfile:
    destfile: "/home/ansible/awx/installer/inventory"
    regexp: '^#?\s*secret_key=.*$'
    line: "secret_key={{ secret_alias }}"
    state: present
  vars:
    secret_alias: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

- name: Configure Awx - Set default Admin Password
  lineinfile:
    destfile: "/home/ansible/awx/installer/inventory"
    regexp: '^#?\s*admin_password=.*$'
    line: "admin_password={{ password.awx }}"
    state: present

- name: Configure Awx - Enable Project Data Dir
  lineinfile:
    destfile: "/home/ansible/awx/installer/inventory"
    regexp: '^#?\s*project_data_dir=.*$'
    line: "project_data_dir=/var/lib/awx/projects"
    state: present

- name: Configure Awx - Disable Demo Data
  lineinfile:
    destfile: "/home/ansible/awx/installer/inventory"
    regexp: '^#?\s*create_preload_data=.*$'
    line: "create_preload_data=False"
    state: present

- name: Configure Awx - Run the AWX installation playbook
  command: "ansible-playbook install.yml -i inventory"
  args:
    chdir: "/home/ansible/awx/installer"
    creates: /etc/awx_playbook_complete
  register: install_awx

# Without Pause here, we will delete data too early and init of awx might fail
- name: Configure Awx - Waiting 3 minute for first Init
  pause:
    minutes: 3
  when: install_awx.changed 
