- name: Initialize AWX - Create vPloy inventory
  tower_inventory:
    name: "vploy"
    description: "vPloy inventory"
    organization: "Default"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"

- name: "Initialize AWX - Create {{ vsphere.address }} group"
  tower_group:
    name: "{{ vsphere.address }}"
    description: "Regroup Server part of {{ vsphere.address }} infrastructure"
    inventory: "vploy"
    variables: "@../config/infra/vsphere.yml"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
  register: group_vsphere

- name: "AWX {{ infra_name }} - Create {{ infra_name }} group"
  tower_group:
    name: "{{ infra_name }}"
    description: "{{ infra_name }} Infrastructure"
    inventory: "vploy"
    variables: 
      network: "{{ network }}"
      dns: "{{ dns }}"
      locale: "{{ locale }}"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
  register: group_infra

- name: "AWX {{ infra_name }} - Create Gateway group"
  tower_group:
    name: "gateway"
    description: "Regroup Gateway Servers"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
  register: group_gateway

- name: "AWX {{ infra_name }} - Create Bastion group"
  tower_group:
    name: "bastion"
    description: "Regroup Bastion Servers"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
  register: group_bastion

- name: "AWX {{ infra_name }} - Create AWX group"
  tower_group:
    name: "awx"
    description: "Regroup Awx Servers"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
  register: group_awx

- name: "AWX {{ infra_name }} - Create Ldap group"
  tower_group:
    name: "ldap"
    description: "Regroup ldap Servers"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
  register: group_ldap

- name: "AWX {{ infra_name }} - Create Jenkins group"
  tower_group:
    name: "jenkins"
    description: "Regroup Jenkins Servers"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
  register: group_jenkins

# Add Management Host in AWX
- name: "AWX {{ infra_name }} - Add Gateway server"
  tower_host:
    name: "gateway.{{ infra_name }}"
    description: "Gateway Management"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
    variables: 
        ansible_host: "{{ network.private_range | ipaddr('address') | ipmath(0) }}"
        ansible_port: "22"
  register: host_gateway

- name: "AWX {{ infra_name }} - Add Bastion server"
  tower_host:
    name: "bastion.{{ infra_name }}"
    description: "bastion Management"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
    variables: 
        ansible_host: "{{ network.private_range | ipaddr('address') | ipmath(1) }}"
        ansible_port: "22"
  register: host_bastion

- name: "AWX {{ infra_name }} - Add AWX server"
  tower_host:
    name: "awx.{{ infra_name }}"
    description: "awx Management"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
    variables: 
        ansible_host: "{{ network.private_range | ipaddr('address') | ipmath(2) }}"
        ansible_port: "22"
  register: host_awx

- name: "AWX {{ infra_name }} - Add Ldap server"
  tower_host:
    name: "ldap.{{ infra_name }}"
    description: "LDAP Management"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
    variables: 
        ansible_host: "{{ network.private_range | ipaddr('address') | ipmath(3) }}"
        ansible_port: "22"
  register: host_ldap

- name: "AWX {{ infra_name }} - Add Jenkins server"
  tower_host:
    name: "jenkins.{{ infra_name }}"
    description: "Jenkins Management"
    inventory: "vploy"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"
    variables: 
        ansible_host: "{{ network.private_range | ipaddr('address') | ipmath(4) }}"
        ansible_port: "22"
  register: host_jenkins

# Link Servers to groups
- name: "AWX {{ infra_name }} - Link Server to groups"
  shell:
    cmd: |
     TOWER_HOST="http://{{ network.public_ip | ipaddr('address') }}" \
     TOWER_USERNAME="admin" \
     TOWER_PASSWORD="{{ password.awx }}" \
     TOWER_VERIFY_SSL=false \
     ~/.local/bin/tower-cli host associate --host "{{ item.host_id }}" --group "{{ item.group_id }}"
  with_items:
    # vsphere group
    - group_id: "{{ group_vsphere.id }}"
      host_id: "{{ host_gateway.id }}"
    - group_id: "{{ group_vsphere.id }}"
      host_id: "{{ host_bastion.id }}"
    - group_id: "{{ group_vsphere.id }}"
      host_id: "{{ host_awx.id }}"
    - group_id: "{{ group_vsphere.id }}"
      host_id: "{{ host_ldap.id }}"
    - group_id: "{{ group_vsphere.id }}"
      host_id: "{{ host_jenkins.id }}"
    # infra group
    - group_id: "{{ group_infra.id }}"
      host_id: "{{ host_gateway.id }}"
    - group_id: "{{ group_infra.id }}"
      host_id: "{{ host_bastion.id }}"
    - group_id: "{{ group_infra.id }}"
      host_id: "{{ host_awx.id }}"
    - group_id: "{{ group_infra.id }}"
      host_id: "{{ host_ldap.id }}"
    - group_id: "{{ group_infra.id }}"
      host_id: "{{ host_jenkins.id }}"
    # gateway group
    - group_id: "{{ group_gateway.id }}"
      host_id: "{{ host_gateway.id }}"
    # bastion group
    - group_id: "{{ group_bastion.id }}"
      host_id: "{{ host_bastion.id }}"
    # awx group
    - group_id: "{{ group_awx.id }}"
      host_id: "{{ host_awx.id }}"
    # ldap group
    - group_id: "{{ group_ldap.id }}"
      host_id: "{{ host_ldap.id }}"
    # jenkins group
    - group_id: "{{ group_jenkins.id }}"
      host_id: "{{ host_jenkins.id }}"