# Create Job Templates
# There is currently an issue on tower_job_template. The credential key is not working
- name: "AWX {{ infra_name }} - Create Base Job Templates"
  tower_job_template:
    name: "{{ job_name | title }} - Base"
    description: "Configure Base {{ job_name | title }}"
    job_type: "run"
    inventory: "vPloy"
    project: "vPloy"
    playbook: "types/{{ job_name }}/base.yml"
    credentials:
      - "Ansible-SSH-Key"
    limit: "{{ job_name }}"
    state: "present"
    tower_config_file: "../generated/tower_cli.cfg"
  register: jobs_base
  loop_control:
    loop_var: job_name
  with_items:
    - awx
    - bastion
    - gateway

- name: "AWX {{ infra_name }} - Create Firewall Job Templates"
  tower_job_template:
    name: "{{ job_name | title }} - Firewall"
    description: "Configure Firewall {{ job_name | title }}"
    job_type: "run"
    inventory: "vPloy"
    project: "vPloy"
    playbook: "types/{{ job_name }}/firewall.yml"
    credentials:
      - "Ansible-SSH-Key"
    limit: "{{ job_name }}"
    state: "present"
    tower_config_file: "../generated/tower_cli.cfg"
  register: jobs_firewall
  loop_control:
    loop_var: job_name
  with_items:
    - awx
    - bastion
    - gateway

- name: "AWX {{ infra_name }} - Create WebServer Job Template on Gateway"
  tower_job_template:
    name: "{{ job_name | title }} - WebServer"
    description: "Configure WebServer {{ job_name | title }}"
    job_type: "run"
    inventory: "vPloy"
    project: "vPloy"
    playbook: "types/{{ job_name }}/webserver.yml"
    credentials:
      - "Ansible-SSH-Key"
    limit: "{{ job_name }}"
    state: "present"
    tower_config_file: "../generated/tower_cli.cfg"
  register: jobs_webserver
  loop_control:
    loop_var: job_name
  with_items:
    - gateway

- name: "AWX {{ infra_name }} - Create Bastion Server Job Template on bastion"
  tower_job_template:
    name: "Bastion - Bastion Server"
    description: "Configure Bastion Server on Bastion"
    job_type: "run"
    inventory: "vPloy"
    project: "vPloy"
    playbook: "types/bastion/bastion.yml"
    credentials:
      - "Ansible-SSH-Key"
      - "vPloy"
    limit: "bastion"
    state: "present"
    tower_config_file: "../generated/tower_cli.cfg"

# Create Workflow Template
- name: "AWX {{ infra_name }} - Create {{ infra_name }} Workflow"
  tower_workflow_template:
    name: "{{ infra_name }}"
    description: "Configure the full {{ infra_name }} Infrastructure"
    organization: Default
    allow_simultaneous: yes
    schema: "{{ lookup('template', 'templates/workflow_all.yml.j2') }}"
    state: present
    tower_config_file: "../generated/tower_cli.cfg"