---
- name: Generate Keys
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: SSH Keys - Creates directory
    file:
      path: ../generated/keys
      state: directory

  - name: SSH Keys - Generate Ansible Key
    shell:
      cmd: ssh-keygen -q -t ed25519 -a 100 -f ../generated/keys/ansible -C "" -N ""
      creates: ../generated/keys/ansible
    register: sshkey_ansible

  - name: SSH Keys - Generate Ssh Gateway Key
    shell:
      cmd: ssh-keygen -q -t ed25519 -a 100 -f ../generated/keys/basion -C "" -N ""
      creates: ../generated/keys/bastion

