---
- name: Generate Keys
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: SSH Keys - Creates directory
    file:
      path: ../generated/keys
      state: directory

  - name: SSH Keys - Generate Ansible Key
    openssh_keypair:
      path: ../generated/keys/ansible
      type: ed25519

  - name: SSH Keys - Generate Ssh Gateway Key
    openssh_keypair:
      path: ../generated/keys/bastion
      type: ed25519
