---
- name: Generate Keys
  hosts: localhost
  connection: local
  tasks:
  - name: SSH Keys - Creates directory
    file:
      path: ../generated/keys
      state: directory

  - name: SSH Keys - Generate Ansible Key
    shell:
      cmd: ssh-keygen -q -t ed25519 -a 100 -f ../generated/keys/ansible -C "" -N ""
      creates: ../generated/keys/ansible
      
  - name: SSH Keys - Generate Bastion Key
    shell:
      cmd: ssh-keygen -q -t ed25519 -a 100 -f ../generated/keys/bastion -C "" -N ""
      creates: ../generated/keys/bastion

