---
- name: Deploy Management Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../config/infra/vsphere.yml
    - ../config/infra/passwords.yml
  tasks:
  - name: Deploy Management - Include Management Tasks
    include_tasks: 
      file: "infra/{{ item }}.yml"
      apply:
        tags:
          - deploy
          - "{{ item }}"
    with_items:
      - management
    tags:
      - always

- name: Deploy Management - Configure Gateway
  hosts: management-gateway
  become: yes
  tasks:
  - name: Deploy Management - Configure Gateway
    include_tasks:
      file: infra/management/01-gateway.yml
      apply:
        tags:
          - management
          - awx
    tags:
      - always

- name: Deploy Management - Install and Configure AWX
  hosts: management-awx
  vars_files:
    - ../config/infra/passwords.yml
  become: yes
  tasks:
  - name: Deploy Management - Install and Configure AWX
    include_tasks:
      file: infra/management/{{ item }}.yml
      apply:
        tags:
          - management
          - awx
    with_items:
      - 02-install_deps_awx
      - 03-install_awx
    tags:
      - always