---
- name: Deploys Infrastructures
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../config/infra/vsphere.yml
    - ../config/infra/passwords.yml
  tasks:

  # Management is a special infrastructure that have to be deployed first
  - name: Deploy Infra - List infrastructure directory
    find:
      paths: ../config/infra
      file_type: directory
      excludes: 'template_factory,management'
    register: infras

  - name: Deploy Infra - Create List of Infrastructure
    set_fact:
      infraNames: "{{ infras.files | map(attribute='path') | map('basename') | list }}"

  - name:  Deploy Infra - Add Management to the list of Infrastructure
    set_fact:
      infraNames: "{{ ['management'] + infraNames }}"

  - name: Deploy Infra - Include Playbook infrastructures
    include: "infra/{{ item }}.yml"
    with_items: "{{ infraNames }}"