---
- name: Deploy Management Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../config/infra/vsphere.yml
    - ../config/infra/passwords.yml
  tasks:
  - name: Deploy Management - Include Management Tasks
    include_tasks: 
      file: "infra/{{ item }}.yml"
      apply:
        tags:
          - deploy
          - "{{ item }}"
    with_items:
      - management
    tags:
      - always
